{% set name = "rmm" %}
{% set version = "22.06.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/rmm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7a57566f099e216ce39f06c0b78ee7b00f22caf326c7201e6251e26883ef8846
  folder: rmm

build:
  number: 0
  skip: true  # [(not linux) or (cuda_compiler_version !=  "11.2") or py<38]
  script_env:
    - INSTALL_PREFIX=${PREFIX}
  script:
    - cd rmm/python
    - SKBUILD_CONFIGURE_OPTIONS="-DFIND_RMM_CPP=ON -DThrust_ROOT=${PREFIX}/include/rapids/thrust/" {{ PYTHON }} -m pip install . --no-deps -vv
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]
  ignore_run_exports:
    - spdlog
    - librmm

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - librmm ={{ version }}
    - python
    - pip
    - cython >=0.29,<0.30
    - spdlog >=1.8.5,<2
    - cuda-python 11.6
    - scikit-build >=0.13.1
  run:
    - python
    - numba >=0.49
    - numpy
    - {{ pin_compatible('cuda-python', min_pin='x.x', max_pin='x.x') }}

test:
  imports:
    - rmm

about:
  home: https://github.com/rapidsai/rmm
  license: Apache-2.0
  license_family: APACHE
  license_file: rmm/LICENSE
  summary: RAPIDS Memory Manager

extra:
  recipe-maintainers:
    - alhad-deshpande
    - leofang
